services:
  pglgma:
    image: postgres:16
    container_name: lgma-postgres
    environment:
      POSTGRES_HOST: "pglgma"
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: full-stack-multi-agent-backend
    ports:
      - "5010:5010"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      HOST: ${HOST}
      BACKEND_PORT: 5010
      SQLALCHEMY_DATABASE_URI: ${DOCKER_SQLALCHEMY_DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - pglgma

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: full-stack-multi-agent-frontend
    ports:
      - "3010:3010"
    volumes:
      - .:/client
    environment:
      PORT: 3010
    depends_on:
      - backend

volumes:
  postgres_data:
