services:
  lgmadb:
    image: postgres:16
    container_name: lgmadb-postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: full-stack-multi-agent-backend
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
    environment:
      HOST: ${HOST}
      BACKEND_PORT: 5001
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - lgmadb

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: full-stack-multi-agent-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./client:/client
    environment:
      PORT: 3001
    depends_on:
      - backend

volumes:
  postgres_data:
