services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: full-stack-multi-agent-backend
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: lgmadb-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: full-stack-multi-agent-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./client:/client
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  postgres_data:
